name: us_citizenship_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy>=1.24.0,<2.0.0
  - pip:
    - transformers>=4.36.0,<5.0.0
    - tensorflow>=2.15.0
    - tf-keras
    - torch
